name: main
on:
  pull_request:
  push:
jobs:
  main:
    name: main
    if: github.event_name == 'pull_request' || github.event_name == 'push'
    runs-on: ubuntu-latest
    container: python:3.6
    steps:
    - name: checkout code
      uses: actions/checkout@v1
    - name: lint codebase
      run: cat README.md
